### ISSUE TITLE
OSPO Questions

### ISSUE THREAD

**Issue by jycouet** [schneider-electric/.github#1]
Hello there 👋
Happy to read that Schneider Electric is moving in the Open Source direction https://www.se.com/ww/en/about-us/open-source/ 🎉

I would like to ask a few questions to help better understand the initiative

## Governance => Who is the `OSPO team` and `stakeholders` ?
Are there representatives from engineering? legal? product management? 
You will maybe build this along the way.

## Get Involved - Contribute to [our projects](https://github.com/orgs/schneider-electric/repositories).
In the list of projects, I see only forks. 
Does that mean that you are taking the ownership of these projects ?
Where should we contribute? 

## Support: Active participation in external open source communities
Will you join programs like https://opensourcepledge.com/ ?

---

Looking forward to learning more about Schneider Electric's open source journey! 🚀

**Comment by selescop** [comment]
Hello,

The OSPO team and stakeholders are mainly what you've described. We have people from engineering team to represent our experts, legal team to make sure we "follow the rules" like license's rights and management team to get approvals. You can find our main sponsors on the link you [mentioned](https://www.se.com/ww/en/about-us/open-source/projects.jsp).

'forks' are the technical way to contribute back to open-source projects on Git. We do not claim ownership, we encourage our developers to participate to project they use/know. These forks are our way to review their proposals and make sure they match Schneider Electric quality before sharing them back to the community.

Thank you for your interest!

**Comment by mickaelgouet-se** [comment]
Hi @jycouet, Thank you for reaching out! You may find more information on our internal OSPO page: current OSPO members, roles, and contribution guidelines. The initiative started as more developers contributed to open source without a proper framework and protection. We want to help the developers to contribute more by providing workflows and a streamlined approval process. As Cédric mentioned, the team includes technical experts, IP, legal, and marketing people; all are volunteers for the same cause. Please let us know if you are interested in joining?
This OSPO is relatively new, and we are continuously improving our processes and documentation. We are looking for contributors who are willing to help!

Check out our internal page!
https://pages.github.schneider-electric.com/InTDigital/se-open-source-docs/organization/

**Comment by jycouet** [comment]
Thank you for your answer. 

I know that `fork` is a way to contribute back. It's also possible to start a new adventure completely separated from the upstream. What misleaded me was this on the home page: `Contribute to [our projects](https://github.com/orgs/schneider-electric/repositories).`.
I usually see individuals forks contributing back to the upstream, not from an org. That's an interesting way to do it 👍.
I guess that like this, your `OSPO team` can check each PR? How do you track the approval ? Or it's not public ?

If I understand well, all this is more for Schneider Electric employees. It's the way to contribute back to open source.

Best luck, 
_//JYC_
